Repository kamera-project/Pre-You, pull requests merged in 2025-06, with the labels that each got.

#14 Feat:add-camera-access-and-photo-capture
  App.jsx
  ios/kamera.xcodeproj/project.pbxproj
  ios/kamera/Info.plist
  src/components/footer/Footer.jsx
  src/screens/CameraScreen.jsx
Labels: implementation

#22 Feat: replace an album thumbnail on capture
  App.jsx
  ios/kamera.xcodeproj/project.pbxproj
  src/components/footer/Footer.jsx
  src/screens/CameraScreen.jsx
  src/store/useCameraStore.js
  src/utils/camera/takePhoto.js
Labels: implementation

#50 refactor: divide functions based on SRP
  src/screens/CameraPreview.jsx
  src/utils/camera/takePhoto.js
Labels: refactor

#51 Fix: re-prompt gallery permission after denial
  ios/Podfile
  ios/Podfile.lock
  ios/kamera.xcodeproj/project.pbxproj
  src/hooks/usePermissions.js
  src/screens/CameraPreview.jsx
Labels: bug

#52 Feat: take photo without overlay
  src/components/overlay/overlaySwitch.jsx
  src/screens/CameraPreview.jsx
  src/store/useCameraStore.js
  src/utils/camera/takePhoto.js
  src/utils/overlay/binaryImageProcessor.js
Labels: implementation

#67 Fix: show the latest photo after removing the photo
  src/screens/GalleryScreen.jsx
Labels: bug

#72 Test: add a test for photo capture and save flow
  __tests__/App.test.tsx
  __tests__/handleTakePhotos.test.js
Labels: test

#77 Chore: replace splash&icon and rename
  ios/kamera.xcodeproj/project.pbxproj
  ios/kamera/Images.xcassets/AppIcon.appiconset/AppStore.1024.1x.png
  ios/kamera/Images.xcassets/AppIcon.appiconset/AppStore.20.2x.png
  ios/kamera/Images.xcassets/AppIcon.appiconset/AppStore.20.3x.png
  ios/kamera/Images.xcassets/AppIcon.appiconset/AppStore.29.2x.png
  ios/kamera/Images.xcassets/AppIcon.appiconset/AppStore.29.3x.png
  ios/kamera/Images.xcassets/AppIcon.appiconset/AppStore.40.2x.png
  ios/kamera/Images.xcassets/AppIcon.appiconset/AppStore.40.3x.png
  ios/kamera/Images.xcassets/AppIcon.appiconset/AppStore.60.2x.png
  ios/kamera/Images.xcassets/AppIcon.appiconset/AppStore.60.3x.png
  ios/kamera/Images.xcassets/AppIcon.appiconset/Contents.json
  ios/kamera/Images.xcassets/AppIcon.appiconset/Pre-You 1024.png
  ios/kamera/Images.xcassets/AppIcon.appiconset/Pre-You 20x20 2x.png
  ios/kamera/Images.xcassets/AppIcon.appiconset/Pre-You 29x29 2x.png
  ios/kamera/Images.xcassets/AppIcon.appiconset/Pre-You 29x29 3x.png
  ios/kamera/Images.xcassets/AppIcon.appiconset/Pre-You 40x40 2x.png
  ios/kamera/Images.xcassets/AppIcon.appiconset/Pre-You 40x40 3x.png
  ios/kamera/Images.xcassets/AppIcon.appiconset/Pre-You 60x60 2x.png
  ios/kamera/Images.xcassets/AppIcon.appiconset/Pre-You 60x60 3x.png
  ios/kamera/Images.xcassets/Image.imageset/Contents.json
  ios/kamera/Images.xcassets/Image.imageset/splash 1x.png
  ios/kamera/Images.xcassets/Image.imageset/splash 2x.png
  ios/kamera/Images.xcassets/Image.imageset/splash 3x.png
  ios/kamera/Images.xcassets/Image.imageset/splashIcon.png
  ios/kamera/Images.xcassets/Image.imageset/splashIcon@2x.png
  ios/kamera/Images.xcassets/Image.imageset/splashIcon@3x.png
  ios/kamera/Info.plist
  ios/kamera/LaunchScreen.storyboard
Labels: style
